import { defineConfig } from "vite";

export default defineConfig({
  // Dynamic city assets are served directly from public/generated by the
  // Fastify service. Copying them into dist duplicates hundreds of megabytes
  // and can race with assets produced while a build is running.
  publicDir: false
});
